-- Lost & Found: what guests leave behind, and getting it back to them.
--
-- The bin by the desk fills up with water bottles, jackets, rings, and single
-- earbuds. Without a record, whether a thing finds its owner depends on the
-- guest thinking to ask and whoever is on shift remembering seeing it. Four
-- tables make that a system instead:
--
--   * `lost_found_items`       — the thing, its photo, and where it is now.
--   * `lost_found_attachments` — one row per photo, mirroring
--                                incident_attachments / shift_note_attachments.
--   * `lost_found_notices`     — one row per person emailed about an item, and
--                                what they said back. A claim link points at a
--                                notice, so a click tells us *who* claimed.
--   * `lost_found_events`      — append-only audit trail, same shape as
--                                incident_events.
--
-- Two things worth knowing before reading the columns:
--
--   * `reference` (LF-2026-0001) is generated by the database, so a staff
--     member can read a case number down the phone without opening a laptop.
--   * Nothing in here is ever auto-donated. The hourly sweep only moves an
--     item to 'due_for_donation'; a person confirms the Furbish drop-off. A
--     row that says 'donated' means someone put it in a bag and drove it there.

-- Human-facing case number. One sequence across all years, matching the
-- incidents convention — the year in the string is for reading, not for
-- uniqueness.
create sequence if not exists public.lost_found_reference_seq;

create or replace function public.next_lost_found_reference()
returns text
language sql
volatile
as $$
  select 'LF-' || to_char(now() at time zone 'America/New_York', 'YYYY') || '-' ||
         lpad(nextval('public.lost_found_reference_seq')::text, 4, '0');
$$;

create table public.lost_found_items (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique default public.next_lost_found_reference(),

  -- unclaimed      — logged, nobody has said it's theirs
  -- claim_pending  — somebody clicked "this is mine"; not handed over yet
  -- claimed        — staff confirmed the claim is good, awaiting pickup
  -- picked_up      — back with its owner. Done.
  -- due_for_donation — past donate_after, waiting on the Furbish run
  -- donated        — dropped at Furbish Thrift
  -- discarded      — binned (a used water bottle nobody will ever want)
  status text not null default 'unclaimed'
    check (status in (
      'unclaimed', 'claim_pending', 'claimed', 'picked_up',
      'due_for_donation', 'donated', 'discarded'
    )),

  -- What it is, in the words a guest would use to recognise it.
  title text not null check (length(title) between 1 and 200),
  -- Distinguishing detail staff check at pickup. Deliberately NOT put in the
  -- guest email: "silver ring, engraved M.K. inside" in an email blast is a
  -- recipe for claiming someone else's ring.
  description text,
  category text not null default 'other'
    check (category in (
      'bottle', 'clothing', 'towel', 'jewelry', 'electronics',
      'bag', 'eyewear', 'keys', 'wallet', 'book', 'toiletries', 'other'
    )),

  -- When staff picked it up off the bench.
  found_at timestamptz not null,
  -- The window it was probably left in. Defaults to a couple of hours before
  -- found_at (set by the app, not here — staff can widen it), and drives which
  -- Momence sessions we offer to email.
  left_window_start timestamptz not null,
  left_window_end timestamptz not null,
  check (left_window_end >= left_window_start),

  -- Where on site it turned up. Free text against LOST_FOUND_AREAS rather than
  -- a check constraint, so the list can shrink or grow without a migration and
  -- rows logged under an older list still read back.
  area text not null default 'other',
  -- Where it lives now: "front desk bin", "shelf B", "staff room hook".
  storage_location text,

  -- Set when staff already know whose it is (matched in the Momence search at
  -- log time). Absent means the unknown-owner path: pick sessions, email the
  -- people who were in them.
  owner_member_id text,
  owner_name text,
  owner_email text,

  -- found_at + 30 days. Stored rather than computed so the deadline is stable
  -- if the policy ever changes, and so the sweep can index on it.
  donate_after timestamptz not null,

  -- Filled by the claim link (never by a staff form).
  claimed_by_email text,
  claimed_by_name text,
  claimed_at timestamptz,

  picked_up_at timestamptz,
  picked_up_by text,
  picked_up_note text,

  donated_at timestamptz,
  donated_by text,

  -- Session email of whoever logged it — set by the route from the session,
  -- never from a request body.
  logged_by text not null,
  logged_by_name text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The sweep's query: unclaimed things whose 30 days are up.
create index lost_found_items_donation_idx
  on public.lost_found_items (status, donate_after);

-- The log's default ordering.
create index lost_found_items_found_idx
  on public.lost_found_items (found_at desc);

create table public.lost_found_attachments (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.lost_found_items (id) on delete cascade,
  -- Object key inside the private `lost-found-media` bucket. Never served
  -- directly: the API route mints a short-lived signed URL per view.
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  kind text not null check (kind in ('photo', 'video', 'document')),
  uploaded_by text not null,
  created_at timestamptz not null default now()
);

create index lost_found_attachments_item_idx
  on public.lost_found_attachments (item_id, created_at);

-- One person we asked about one item. Also the thing a claim token addresses:
-- the token carries a notice id, so "this is mine" identifies the claimant
-- without asking them to type anything.
create table public.lost_found_notices (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.lost_found_items (id) on delete cascade,
  email text not null,
  name text,
  -- Momence member id when we had one.
  member_id text,
  -- Which session put them in the building. Null for a known-owner send.
  session_id text,
  session_name text,
  session_starts_at timestamptz,
  sent_at timestamptz not null default now(),
  responded_at timestamptz,
  response text check (response in ('claimed', 'not_mine')),
  -- One ask per person per item: a re-send after adding more sessions must not
  -- email the same guest twice, and this is the database's half of the
  -- send_key idempotency in lib/email/send.ts.
  unique (item_id, email)
);

create index lost_found_notices_item_idx
  on public.lost_found_notices (item_id, sent_at);

create table public.lost_found_events (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.lost_found_items (id) on delete cascade,
  action text not null
    check (action in (
      'created', 'updated', 'status_changed',
      'attachment_added', 'attachment_removed',
      'notified', 'claim_received', 'picked_up', 'donated', 'discarded',
      'donation_due'
    )),
  -- Session email of whoever did it, 'cron' for the sweep, or 'guest' for a
  -- claim-link click.
  actor text not null,
  detail jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamptz not null default now()
);

create index lost_found_events_item_idx
  on public.lost_found_events (item_id, created_at);

alter table public.lost_found_items enable row level security;
alter table public.lost_found_attachments enable row level security;
alter table public.lost_found_notices enable row level security;
alter table public.lost_found_events enable row level security;

-- App access is service-role (bypasses RLS) and gated in-route by
-- requirePage/hasLostFoundManage; these policies are the forward-looking
-- convention the other admin tables follow. No delete policy on
-- lost_found_events: the audit trail is append-only.
create policy "admins can select lost found items"
  on public.lost_found_items for select
  using (public.is_admin());

create policy "admins can insert lost found items"
  on public.lost_found_items for insert
  with check (public.is_admin());

create policy "admins can update lost found items"
  on public.lost_found_items for update
  using (public.is_admin());

create policy "admins can delete lost found items"
  on public.lost_found_items for delete
  using (public.is_admin());

create policy "admins can select lost found attachments"
  on public.lost_found_attachments for select
  using (public.is_admin());

create policy "admins can insert lost found attachments"
  on public.lost_found_attachments for insert
  with check (public.is_admin());

create policy "admins can delete lost found attachments"
  on public.lost_found_attachments for delete
  using (public.is_admin());

create policy "admins can select lost found notices"
  on public.lost_found_notices for select
  using (public.is_admin());

create policy "admins can insert lost found notices"
  on public.lost_found_notices for insert
  with check (public.is_admin());

create policy "admins can update lost found notices"
  on public.lost_found_notices for update
  using (public.is_admin());

create policy "admins can select lost found events"
  on public.lost_found_events for select
  using (public.is_admin());

create policy "admins can insert lost found events"
  on public.lost_found_events for insert
  with check (public.is_admin());

-- Private bucket for item photos. Its own bucket rather than sharing
-- incident-media: a signed-URL mistake in one tool should not reach the
-- other's media, and incident photos are far more sensitive. Same shape and
-- limits as the other two.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'lost-found-media',
  'lost-found-media',
  false,
  52428800,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'image/gif',
    'video/mp4', 'video/quicktime', 'video/webm',
    'application/pdf'
  ]
)
on conflict (id) do nothing;

comment on table public.lost_found_items is
  'Items guests left behind, logged from /admin/lost-found: what it is, where it was found, who has been asked about it, and how it left our hands. Unclaimed items are flagged for donation to Furbish Thrift after 30 days — flagged by cron, donated only by a person.';
comment on table public.lost_found_attachments is
  'Photos of a lost-and-found item. Objects live in the private lost-found-media bucket and are only ever served through short-lived signed URLs.';
comment on table public.lost_found_notices is
  'One row per person emailed about an item, and their answer. A claim link carries a signed notice id, so a "this is mine" click identifies the claimant.';
comment on table public.lost_found_events is
  'Append-only audit trail for a lost-and-found item: logging, edits, who was emailed, claims, pickup, and donation.';
