-- Incident reporting: the bathhouse's log of everything that went wrong —
-- slips and falls, burns, heat illness, chemical exposure, altercations,
-- near misses. Staff file a report from /admin/incidents/new the moment the
-- situation is stable; the record is what insurance, OSHA-style follow-up,
-- and our own corrective actions all read from later.
--
-- Three tables:
--   incidents             the report itself, one row per event
--   incident_attachments  photos/video/documents in the private storage bucket
--   incident_events       append-only audit trail — every filing, edit,
--                         status change, note, and attachment, with who/when
--
-- Design notes:
--   * Every "who" column holds a session email, never a value from the request
--     body — the reporter cannot claim to be someone else.
--   * `reference` (INC-2026-0001) is generated by the database so the paper
--     trail has a short human-quotable id from the moment of filing.
--   * incidents rows are never deleted in normal operation (admins can, for
--     test rows); a mistaken report is voided via status, which keeps the
--     original text in the audit trail.
--   * People involved live in jsonb rather than side tables: a report is read
--     as one document, and the shape varies (a guest with an injury vs a
--     witness who just saw it).

-- Human-facing case number. A single sequence across all years keeps the
-- number unique on its own; the year prefix is for readability.
create sequence if not exists public.incident_reference_seq;

create or replace function public.next_incident_reference()
returns text
language sql
volatile
as $$
  select 'INC-' || to_char(now() at time zone 'America/New_York', 'YYYY') || '-' ||
         lpad(nextval('public.incident_reference_seq')::text, 4, '0');
$$;

create table public.incidents (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique default public.next_incident_reference(),

  -- Lifecycle. 'submitted' is what staff file; a manager moves it through
  -- review to resolved/closed. 'voided' retires a duplicate or mistaken
  -- report without erasing it.
  status text not null default 'submitted'
    check (status in ('submitted', 'under_review', 'action_required', 'resolved', 'closed', 'voided')),

  -- What happened.
  category text not null check (category in (
    'slip_fall', 'burn_heat', 'cut_laceration', 'heat_illness', 'cold_exposure',
    'fainting', 'breathing_difficulty', 'allergic_reaction', 'chemical_exposure',
    'water_quality', 'medical_event', 'equipment_failure', 'facility_damage',
    'fire_smoke', 'altercation', 'harassment', 'intoxication', 'policy_violation',
    'theft_security', 'hygiene_contamination', 'near_miss', 'other'
  )),
  severity text not null check (severity in ('near_miss', 'minor', 'moderate', 'severe', 'critical')),

  -- When it happened vs when staff became aware. occurred_at is the legal
  -- timestamp; reported_at (below) is when the report was filed, and the gap
  -- between them matters in a review.
  occurred_at timestamptz not null,
  discovered_at timestamptz,

  -- Where, within the building. `area` is a code from lib/incidents/types.ts;
  -- `area_detail` is the free-text specifics ("second bench, left sauna").
  area text not null,
  area_detail text,

  -- People. Each entry of affected_people:
  --   { role, name, phone, email, member_id, injured, injury_nature,
  --     body_parts[], notes }
  -- Each entry of witnesses: { name, phone, email, is_staff, statement }
  affected_people jsonb not null default '[]'::jsonb,
  witnesses jsonb not null default '[]'::jsonb,
  -- Emails/names of staff working at the time, for follow-up interviews.
  staff_present text[] not null default '{}',

  -- The narrative. `description` is the factual account; `immediate_actions`
  -- is what staff did about it. Both required — a report without either is
  -- not usable in a review.
  description text not null check (length(btrim(description)) > 0),
  immediate_actions text not null check (length(btrim(immediate_actions)) > 0),

  -- Response taken.
  first_aid_given boolean not null default false,
  first_aid_by text,
  ems_called boolean not null default false,
  ems_called_at timestamptz,
  police_called boolean not null default false,
  transported_to_hospital boolean not null default false,
  treatment_refused boolean not null default false,
  guest_left_premises boolean,
  guest_informed_of_report boolean,

  -- Conditions that contributed (codes from lib/incidents/types.ts) and the
  -- environmental readings that matter for burns and heat illness.
  contributing_factors text[] not null default '{}',
  equipment_involved text,
  sauna_temp_f numeric(5, 1),
  water_temp_f numeric(5, 1),

  -- Follow-up and closure.
  follow_up_required boolean not null default false,
  follow_up_notes text,
  corrective_actions text,
  resolution_notes text,
  resolved_at timestamptz,
  resolved_by text,

  -- Who filed it and when. Always taken from the authenticated session.
  reported_by text not null,
  reported_by_name text,
  reported_at timestamptz not null default now(),

  -- Manager review.
  reviewed_by text,
  reviewed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- A closed-out report has to say who closed it.
  constraint incidents_resolution_attributed
    check ((resolved_at is null) = (resolved_by is null))
);

create trigger incidents_set_updated_at
  before update on public.incidents
  for each row execute function public.set_updated_at();

-- The log lists newest-first; the open queue filters by status; the "my
-- reports" view filters by reporter.
create index incidents_occurred_idx on public.incidents (occurred_at desc);
create index incidents_status_idx on public.incidents (status, occurred_at desc);
create index incidents_reported_by_idx on public.incidents (reported_by, occurred_at desc);
create index incidents_severity_idx on public.incidents (severity, occurred_at desc);

create table public.incident_attachments (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.incidents (id) on delete cascade,
  -- Object key inside the private `incident-media` bucket. Never served
  -- directly: /api/admin/incident-media mints a short-lived signed URL per
  -- view, so media stays behind the same gate as the report.
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0),
  kind text not null check (kind in ('photo', 'video', 'document')),
  caption text,
  uploaded_by text not null,
  created_at timestamptz not null default now()
);

create index incident_attachments_incident_idx
  on public.incident_attachments (incident_id, created_at);

-- Append-only audit trail. Nothing here is ever updated or deleted while the
-- incident lives: "who changed what, when" is the reason this system exists.
create table public.incident_events (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.incidents (id) on delete cascade,
  action text not null check (action in (
    'created', 'updated', 'status_changed', 'note_added',
    'attachment_added', 'attachment_removed', 'notified'
  )),
  actor text not null,
  -- For 'updated'/'status_changed': { field: { from, to } } per changed field.
  -- For attachments: { file_name, kind }. For 'notified': { recipients }.
  detail jsonb not null default '{}'::jsonb,
  -- Free-text follow-up for 'note_added'.
  note text,
  created_at timestamptz not null default now()
);

create index incident_events_incident_idx
  on public.incident_events (incident_id, created_at);

alter table public.incidents enable row level security;
alter table public.incident_attachments enable row level security;
alter table public.incident_events enable row level security;

-- App access is service-role (bypasses RLS) and gated in-route by
-- requirePage/requireAdmin; these policies are the forward-looking convention
-- the other admin tables follow. No delete policy on incident_events: the
-- audit trail is append-only.
create policy "admins can select incidents"
  on public.incidents for select
  using (public.is_admin());

create policy "admins can insert incidents"
  on public.incidents for insert
  with check (public.is_admin());

create policy "admins can update incidents"
  on public.incidents for update
  using (public.is_admin());

create policy "admins can delete incidents"
  on public.incidents for delete
  using (public.is_admin());

create policy "admins can select incident attachments"
  on public.incident_attachments for select
  using (public.is_admin());

create policy "admins can insert incident attachments"
  on public.incident_attachments for insert
  with check (public.is_admin());

create policy "admins can delete incident attachments"
  on public.incident_attachments for delete
  using (public.is_admin());

create policy "admins can select incident events"
  on public.incident_events for select
  using (public.is_admin());

create policy "admins can insert incident events"
  on public.incident_events for insert
  with check (public.is_admin());

-- Private bucket for incident photos/video. Private is the point: the media
-- shows guests, injuries, and sometimes medical detail, so every read goes
-- through a signed URL minted by the gated API route. 50 MB covers a phone
-- video clip; the API caps per-file size to the same number.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'incident-media',
  'incident-media',
  false,
  52428800,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif', 'image/gif',
    'video/mp4', 'video/quicktime', 'video/webm',
    'application/pdf'
  ]
)
on conflict (id) do nothing;

comment on table public.incidents is
  'Bathhouse incident reports: what happened, to whom, what staff did, and how it was resolved. Filed by staff from /admin/incidents; who filed it and when are taken from the session, never the request body.';
comment on table public.incident_attachments is
  'Photos, video, and documents attached to an incident report. Objects live in the private incident-media bucket and are only ever served through short-lived signed URLs.';
comment on table public.incident_events is
  'Append-only audit trail for an incident: filing, every field edit with before/after, status changes, follow-up notes, and attachment activity.';
