// Campaign performance report. Short-link clicks come from the shared Upstash
// store; visits, signups, bookings, and pack/membership purchases are
// attributed by first-touch utm_campaign in PostHog (with click inference
// filling in for bookers and buyers who never identified on the site).
//
// utm_campaign values observed in the wild are free text (e.g. "Instagram Bio
// Links" from hand-built links), while campaigns are stored under their
// slugified name ("instagram-bio-links"). Every campaign value is normalized
// through slugifyCampaign before joining so the variants roll up together.
//
// Short links generated by the Campaigns tool are joined by the code stored on
// the link record; older ones (from the free-form UTM Assist era, or minted by
// hand) only by the utm_campaign baked into their URL.
//
// The same rollups are also grouped by utm_source (`sources`), so a channel
// like the newsletter or the automated lifecycle emails can be read across
// every campaign its links belonged to.
//
// `?campaign=<slug>` narrows a report to one campaign for the detail page. It
// is applied after the cache, so the detail page never costs a PostHog query
// of its own.

import {
  getRedis,
  getShortLinks,
  listCampaignsWithLinks,
  listShortLinks,
  slugifyCampaign,
  utmCampaignOfUrl,
  utmSourceOfUrl,
} from '@pyre/webhook-core';
import type { APIRoute } from 'astro';
import {
  getEventLastSeen,
  isPostHogQueryConfigured,
  queryHogQL,
} from '@/lib/analytics/posthog-query';
import { requirePage } from '@/lib/auth/admin';
import {
  BOOKING,
  BOOKING_BACKFILL,
  bucketColumn,
  type ConversionColumn,
  type ConversionCounts,
  conversionCounts,
  PURCHASE,
  PURCHASE_BUCKET_PREFIX,
  SIGNUP_INTRO,
  SIGNUP_MAILING,
} from '@/lib/campaigns/conversion-buckets';
import { describeLink } from '@/lib/campaigns/describe';

const JSON_HEADERS = { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' };

// v3: rows gained the purchase columns (v2 added `sources`); an older entry
// must never be served to a UI that expects them.
const CACHE_PREFIX = 'cache:campaign-perf:v3:';
const CACHE_TTL_SECONDS = 5 * 60;
// Last report that came back with PostHog data intact, kept much longer so a
// transient PostHog outage degrades to stale numbers instead of an empty table.
const LAST_GOOD_PREFIX = 'cache:campaign-perf:v3:last-good:';
const LAST_GOOD_TTL_SECONDS = 7 * 24 * 60 * 60;
const ALLOWED_DAYS = [7, 30, 90];

// PostHog's query pool is slow and flaky (see posthog-query.ts); the function
// has a 60s ceiling (astro.config.mjs), so budget the query and its retries
// under that and leave room for the Redis round-trips.
const QUERY_BUDGET_MS = 45_000;
const PRESENCE_BUDGET_MS = 10_000;
// An event that has not been ingested in this long is treated as missing —
// i.e. an instrumentation gap rather than a quiet stretch.
const PRESENCE_WINDOW_DAYS = 180;
// HogQL silently caps results at 100 rows without an explicit LIMIT.
const ROW_LIMIT = 1000;

// Conversion events attributed via the person's first-touch utm_campaign.
// BOOKING_BACKFILL is deliberately absent: it is counted into the bookings
// column but must not trip the instrumentation-gap check.
const CONVERSION_EVENTS = [SIGNUP_INTRO, SIGNUP_MAILING, BOOKING, PURCHASE];

/** Per-campaign numbers; the conversion columns come from ConversionCounts. */
interface CampaignRow extends ConversionCounts {
  id: string;
  name: string;
  slug: string;
  createdAt: number;
  linkCount: number;
  shortlinks: Array<{ code: string; label: string; clicks: number; placementKey: string }>;
  shortlinkClicks: number;
  pageviews: number;
  visitors: number;
}

/** The same numbers rolled up by utm_source across every campaign. */
interface SourceRow extends ConversionCounts {
  source: string;
  shortlinkClicks: number;
  pageviews: number;
  visitors: number;
}

interface PerformanceResponse {
  generatedAt: string;
  days: number;
  cached: boolean;
  /** True when PostHog failed and these are the numbers from the last report
   * that succeeded (see generatedAt); posthog.error carries the failure. */
  stale: boolean;
  campaigns: CampaignRow[];
  sources: SourceRow[];
  unattributed: Array<{ slug: string; pageviews: number; visitors: number }>;
  posthog: { configured: boolean; missingEvents: string[]; error: string | null };
}

const sqlList = (events: readonly string[]) => events.map((e) => `'${e}'`).join(', ');

// Campaign (or source) a conversion is attributed to: first-touch via the
// person's $initial_utm_*, else the event-level attributed_utm_* stamped by
// click inference on bookings and purchases whose buyer never identified on
// the site (their person has no first-touch data). Backfill events count ONLY
// by their stamped value — their person properties reflect ingestion
// (backfill run) time, not booking time.
function attributedExpr(field: 'campaign' | 'source'): string {
  return `lower(if(event = '${BOOKING_BACKFILL}',
             nullif(toString(properties.attributed_utm_${field}), ''),
             coalesce(
               nullif(toString(person.properties.$initial_utm_${field}), ''),
               if(event IN ('${BOOKING}', '${PURCHASE}'),
                  nullif(toString(properties.attributed_utm_${field}), ''),
                  NULL)
             )))`;
}

// Conversions group by "bucket": the event name, except purchases, which carry
// their purchase_kind so intro offers, packs and memberships split in the same
// GROUP BY (mapped to columns by lib/campaigns/conversion-buckets.ts).
const BUCKET_EXPR = `if(event = '${PURCHASE}',
             concat('${PURCHASE_BUCKET_PREFIX}',
                    coalesce(nullif(toString(properties.purchase_kind), ''), 'unknown')),
             event)`;

// Traffic and conversions in a single round-trip. Every query to PostHog's
// personal-API-key pool pays several seconds of queueing and a real chance of a
// 503, regardless of how little data it touches, so the rollups ride the same
// request as UNION ALL branches (each branch keeps its own plan, and the person
// join stays confined to the conversion side). Rows come back tagged by
// `section`; the `people` column is only meaningful for traffic. The `campaign`
// column holds the utm_source in the *_source sections (the name is shared so
// the branches union).
function buildRollupQuery(days: number): string {
  const traffic = (section: string, field: 'campaign' | 'source') => `
    SELECT '${section}' AS section,
           lower(toString(properties.utm_${field})) AS campaign,
           event AS bucket,
           count() AS n,
           count(DISTINCT person_id) AS people
    FROM events
    WHERE event = '$pageview'
      AND properties.utm_${field} IS NOT NULL
      AND properties.utm_${field} != ''
      AND timestamp >= now() - INTERVAL ${days} DAY
    GROUP BY campaign, bucket
    ORDER BY n DESC
    LIMIT ${ROW_LIMIT}`;

  const conversion = (section: string, field: 'campaign' | 'source') => `
    SELECT '${section}' AS section,
           ${attributedExpr(field)} AS campaign,
           ${BUCKET_EXPR} AS bucket,
           count() AS n,
           0 AS people
    FROM events
    WHERE event IN (${sqlList([...CONVERSION_EVENTS, BOOKING_BACKFILL])})
      AND timestamp >= now() - INTERVAL ${days} DAY
      AND campaign IS NOT NULL
      AND campaign != ''
    GROUP BY campaign, bucket
    ORDER BY n DESC
    LIMIT ${ROW_LIMIT}`;

  return [
    // Pageviews carrying utm_campaign, grouped by campaign value.
    traffic('traffic', 'campaign'),
    conversion('conversion', 'campaign'),
    // The same two rollups keyed by utm_source.
    traffic('traffic_source', 'source'),
    conversion('conversion_source', 'source'),
  ].join('\n    UNION ALL');
}

// Which conversion events reach PostHog at all — flags instrumentation gaps
// like booking_completed never arriving. Read from the event-definition
// registry instead of scanning events: a 180-day ClickHouse scan reaches into
// PostHog's cold partitions and reliably blew the query timeout, while the
// registry answers from Postgres in a couple of seconds. Best effort: on
// failure nothing is flagged rather than raising a false alarm.
async function findMissingEvents(): Promise<string[]> {
  try {
    const lastSeen = await getEventLastSeen(CONVERSION_EVENTS, {
      signal: AbortSignal.timeout(PRESENCE_BUDGET_MS),
    });
    const cutoff = Date.now() - PRESENCE_WINDOW_DAYS * 24 * 60 * 60 * 1000;
    return CONVERSION_EVENTS.filter((event) => {
      const seenAt = lastSeen.get(event);
      return !seenAt || seenAt.getTime() < cutoff;
    });
  } catch (err) {
    console.warn('[campaign-performance] event presence check skipped:', err);
    return [];
  }
}

async function buildReport(days: number): Promise<PerformanceResponse> {
  const posthog: PerformanceResponse['posthog'] = {
    configured: isPostHogQueryConfigured(),
    missingEvents: [],
    error: null,
  };

  // slug (lowercase) -> traffic / conversion rollups from PostHog
  const traffic = new Map<string, { pageviews: number; visitors: number }>();
  const conversions = new Map<string, Map<ConversionColumn, number>>();
  // utm_source (lowercase) -> the same rollups
  const sourceTraffic = new Map<string, { pageviews: number; visitors: number }>();
  const sourceConversions = new Map<string, Map<ConversionColumn, number>>();

  const campaignsWithLinks = await listCampaignsWithLinks();
  const explicitCodes = campaignsWithLinks.flatMap((c) =>
    c.links.map((l) => l.shortCode).filter(Boolean)
  );

  const [shortlinksByCode, shortlinkPage, rollupRows, missingEvents] = await Promise.all([
    getShortLinks(explicitCodes),
    listShortLinks(500, 0),
    posthog.configured
      ? queryHogQL(buildRollupQuery(days), {
          signal: AbortSignal.timeout(QUERY_BUDGET_MS),
        }).catch((err: unknown) => {
          posthog.error = err instanceof Error ? err.message : 'PostHog query failed';
          return null;
        })
      : Promise.resolve(null),
    posthog.configured ? findMissingEvents() : Promise.resolve([]),
  ]);
  posthog.missingEvents = missingEvents;

  if (rollupRows) {
    for (const row of rollupRows) {
      const [section, rawKey, bucket, count, people] = row as [
        string,
        string,
        string,
        number,
        number,
      ];
      const bySource = section.endsWith('_source');
      // Campaign values slugify so free-text variants roll up; sources are
      // already short tokens and only need lowercasing.
      const key = bySource
        ? (rawKey ?? '').trim().toLowerCase()
        : rawKey
          ? slugifyCampaign(rawKey)
          : '';
      if (!key) continue;
      const trafficMap = bySource ? sourceTraffic : traffic;
      const conversionMap = bySource ? sourceConversions : conversions;
      if (section === 'traffic' || section === 'traffic_source') {
        // Sum across raw variants that slugify to the same campaign. Visitors can
        // double-count a person seen under two variants; acceptable for a report.
        const prev = trafficMap.get(key);
        trafficMap.set(key, {
          pageviews: (prev?.pageviews ?? 0) + Number(count),
          visitors: (prev?.visitors ?? 0) + Number(people),
        });
      } else {
        // Backfilled attribution counts as a booking (a backfill event only
        // exists for bookings with no attribution of their own, so no double
        // count); renewals and uncounted purchase kinds map to nothing.
        const column = bucketColumn(bucket);
        if (!column) continue;
        const byColumn = conversionMap.get(key) ?? new Map<ConversionColumn, number>();
        byColumn.set(column, (byColumn.get(column) ?? 0) + Number(count));
        conversionMap.set(key, byColumn);
      }
    }
  }

  // Legacy join: group recent shortlinks by the utm_campaign baked into their
  // destination URL, for links that carry no code of their own.
  const shortlinksBySlug = new Map<string, Array<CampaignRow['shortlinks'][number]>>();
  for (const link of shortlinkPage.links) {
    const slug = utmCampaignOfUrl(link.url);
    if (!slug) continue;
    const list = shortlinksBySlug.get(slug) ?? [];
    list.push({
      code: link.code,
      label: link.label,
      clicks: Number(link.clicks) || 0,
      placementKey: '',
    });
    shortlinksBySlug.set(slug, list);
  }

  const knownSlugs = new Set<string>();
  // Short-link clicks by utm_source: a generated link knows its source; a
  // legacy short link only through its URL. Codes claimed by a link are
  // skipped in the legacy pass so nothing counts twice.
  const sourceClicks = new Map<string, number>();
  const claimedCodes = new Set<string>();
  const addSourceClicks = (source: string | null, clicks: number) => {
    if (!source) return;
    sourceClicks.set(source, (sourceClicks.get(source) ?? 0) + clicks);
  };

  const campaigns: CampaignRow[] = campaignsWithLinks.map(({ campaign, links }) => {
    const slug = campaign.slug.toLowerCase();
    knownSlugs.add(slug);

    // Explicit codes first, labelled by placement; then any legacy shortlink
    // under this slug that no link claims.
    const shortlinks: CampaignRow['shortlinks'] = [];
    const claimed = new Set<string>();
    for (const link of links) {
      const short = link.shortCode ? shortlinksByCode.get(link.shortCode) : undefined;
      if (!short) continue;
      claimed.add(short.code);
      claimedCodes.add(short.code);
      addSourceClicks(link.source.trim().toLowerCase() || null, Number(short.clicks) || 0);
      // The placement (with partner / custom values spelled out), then the
      // staff note if there is one.
      const described = describeLink(link);
      const label = link.label ? `${described} (${link.label})` : described;
      shortlinks.push({
        code: short.code,
        label,
        clicks: Number(short.clicks) || 0,
        placementKey: link.placementKey,
      });
    }
    for (const legacy of shortlinksBySlug.get(slug) ?? []) {
      if (!claimed.has(legacy.code)) shortlinks.push(legacy);
    }

    return {
      id: campaign.id,
      name: campaign.name,
      slug: campaign.slug,
      createdAt: Number(campaign.createdAt),
      linkCount: links.length,
      shortlinks,
      shortlinkClicks: shortlinks.reduce((sum, s) => sum + s.clicks, 0),
      pageviews: traffic.get(slug)?.pageviews ?? 0,
      visitors: traffic.get(slug)?.visitors ?? 0,
      ...conversionCounts(conversions.get(slug)),
    };
  });

  for (const link of shortlinkPage.links) {
    if (claimedCodes.has(link.code)) continue;
    addSourceClicks(utmSourceOfUrl(link.url), Number(link.clicks) || 0);
  }

  const sourceKeys = new Set<string>([
    ...sourceTraffic.keys(),
    ...sourceConversions.keys(),
    ...sourceClicks.keys(),
  ]);
  const sources: SourceRow[] = [...sourceKeys]
    .map((source) => ({
      source,
      shortlinkClicks: sourceClicks.get(source) ?? 0,
      pageviews: sourceTraffic.get(source)?.pageviews ?? 0,
      visitors: sourceTraffic.get(source)?.visitors ?? 0,
      ...conversionCounts(sourceConversions.get(source)),
    }))
    .sort((a, b) => b.pageviews - a.pageviews || b.shortlinkClicks - a.shortlinkClicks);

  // utm_campaign values seen in PostHog with no stored campaign — automated
  // journeys (their id is their campaign) and links built by hand.
  const unattributed = [...traffic.entries()]
    .filter(([slug]) => !knownSlugs.has(slug))
    .map(([slug, t]) => ({ slug, pageviews: t.pageviews, visitors: t.visitors }))
    .sort((a, b) => b.pageviews - a.pageviews);

  return {
    generatedAt: new Date().toISOString(),
    days,
    cached: false,
    stale: false,
    campaigns,
    sources,
    unattributed,
    posthog,
  };
}

/** Narrow a report to one campaign slug for the detail page. */
function onlyCampaign(report: PerformanceResponse, slug: string | null): PerformanceResponse {
  if (!slug) return report;
  const wanted = slugifyCampaign(slug);
  return {
    ...report,
    campaigns: report.campaigns.filter((c) => c.slug.toLowerCase() === wanted),
    unattributed: [],
  };
}

export const GET: APIRoute = async ({ cookies, url }) => {
  const gate = await requirePage(cookies, '/admin/campaigns');
  if (gate instanceof Response) return gate;

  const daysRaw = Number.parseInt(url.searchParams.get('days') ?? '', 10);
  const days = ALLOWED_DAYS.includes(daysRaw) ? daysRaw : 30;
  const campaignSlug = url.searchParams.get('campaign');

  const respond = (report: PerformanceResponse) =>
    new Response(JSON.stringify(onlyCampaign(report, campaignSlug)), {
      status: 200,
      headers: JSON_HEADERS,
    });

  try {
    const redis = getRedis();
    const cacheKey = `${CACHE_PREFIX}${days}`;

    if (url.searchParams.get('fresh') !== '1') {
      const cachedReport = await redis?.get<PerformanceResponse>(cacheKey);
      if (cachedReport) return respond({ ...cachedReport, cached: true });
    }

    const report = await buildReport(days);
    const lastGoodKey = `${LAST_GOOD_PREFIX}${days}`;

    if (report.posthog.error) {
      // Never cache a failed report as if it were the answer for the next five
      // minutes. Serve the last successful numbers instead, flagged stale, so
      // the page still reads while PostHog recovers.
      const lastGood = await redis?.get<PerformanceResponse>(lastGoodKey);
      const fallback: PerformanceResponse = lastGood
        ? {
            ...lastGood,
            cached: true,
            stale: true,
            posthog: { ...lastGood.posthog, error: report.posthog.error },
          }
        : report;
      return respond(fallback);
    }

    await Promise.all([
      redis?.set(cacheKey, report, { ex: CACHE_TTL_SECONDS }),
      report.posthog.configured
        ? redis?.set(lastGoodKey, report, { ex: LAST_GOOD_TTL_SECONDS })
        : null,
    ]);

    return respond(report);
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: JSON_HEADERS,
    });
  }
};
